Repository MemTensor/MemOS, pull requests merged in 2025-07, with the labels that each got.

#23 fix(example): correct ParsedTaskGoal usage and add unrelated memory for testing
  examples/basic_modules/tree_textual_memory_reasoner.py
Labels: [TreeTextualMemory]

#120 build: optimize dependencies management
  .github/workflows/python-tests.yml
  Makefile
  README.md
  evaluation/README.md
  poetry.lock
  pyproject.toml
  scripts/check_dependencies.py
  src/memos/chunkers/sentence_chunker.py
  src/memos/dependency.py
  src/memos/embedders/ark.py
  src/memos/embedders/sentence_transformer.py
  src/memos/graph_dbs/neo4j.py
  src/memos/llms/hf.py
  src/memos/mem_scheduler/modules/rabbitmq_service.py
  src/memos/mem_scheduler/modules/redis_service.py
  src/memos/mem_scheduler/modules/retriever.py
  src/memos/memories/activation/kv.py
  src/memos/memories/activation/vllmkv.py
  src/memos/memories/textual/tree_text_memory/organize/reorganizer.py
  src/memos/parsers/markitdown.py
  src/memos/vec_dbs/qdrant.py
  tests/chunkers/test_sentence_chunker.py
  tests/vec_dbs/test_qdrant.py
Labels: good first issue

#142 refactor: improve architecture and configurations for memory scheduler
  examples/data/config/mem_scheduler/general_scheduler_config.yaml
  examples/data/config/mem_scheduler/memos_config_w_scheduler.yaml
  examples/data/config/mem_scheduler/memos_config_w_scheduler_and_openai.yaml
  examples/mem_os/chat_w_scheduler.py
  examples/mem_scheduler/memos_w_scheduler.py
  examples/mem_scheduler/memos_w_scheduler_for_test.py
  examples/mem_scheduler/rabbitmq_example.py
  examples/mem_scheduler/redis_example.py
  examples/mem_scheduler/try_schedule_modules.py
  src/memos/configs/mem_scheduler.py
  src/memos/mem_os/core.py
  src/memos/mem_os/main.py
  src/memos/mem_os/product.py
  src/memos/mem_scheduler/base_scheduler.py
  src/memos/mem_scheduler/general_scheduler.py
  src/memos/mem_scheduler/modules/base.py
  src/memos/mem_scheduler/modules/dispatcher.py
  src/memos/mem_scheduler/modules/misc.py
  src/memos/mem_scheduler/modules/monitor.py
  src/memos/mem_scheduler/modules/rabbitmq_service.py
  src/memos/mem_scheduler/modules/retriever.py
  src/memos/mem_scheduler/modules/scheduler_logger.py
  src/memos/mem_scheduler/modules/schemas.py
  src/memos/mem_scheduler/mos_for_test_scheduler.py
  src/memos/mem_scheduler/schemas/__init__.py
  src/memos/mem_scheduler/schemas/general_schemas.py
  src/memos/mem_scheduler/schemas/message_schemas.py
  src/memos/mem_scheduler/schemas/monitor_schemas.py
  src/memos/mem_scheduler/utils.py
  src/memos/mem_scheduler/utils/__init__.py
  src/memos/mem_scheduler/utils/filter_utils.py
  src/memos/mem_scheduler/utils/misc_utils.py
  src/memos/memories/activation/item.py
  src/memos/memories/textual/base.py
  src/memos/templates/mem_scheduler_prompts.py
  tests/mem_scheduler/test_retriever.py
  tests/mem_scheduler/test_scheduler.py
Labels: bug, enhancement, [MemScheduler]
